install
Installer improved.

diff --git a/weby b/weby
--- a/weby
+++ b/weby
@@ -1,13 +1,24 @@
 #!/bin/bash
 # Webinoly Installation Script.
 
+readonly os_supported_latest=("noble" "24.04" "1.18.0")   # Newest Ubuntu supported, including first Webinoly version with full support.
+readonly os_supported_stable=("jammy" "22.04")            # Supported in all versions available of Webinoly.
+readonly os_supported_legacy=("focal" "20.04" "1.19.1")   # Oldest Ubuntu. Partially supported. No new installations, updates only! Webinoly version when support was removed.
+
+# 24.04 noble - 1.18.0
+# 22.04 jammy - 1.16.6
+# 20.04 focal - 1.12.0
+# 18.04 bionic - 1.4.2
+# 16.04 xenial - 1.0.0
+
 # Check OS support
-distr=`echo $(lsb_release -i | cut -d':' -f 2)`
-osver=`echo $(lsb_release -c | cut -d':' -f 2)`
+distr=$(awk -F= '/^ID=/{print $2}' /etc/os-release)
+osver=$(awk -F= '/^VERSION_CODENAME=/{print $2}' /etc/os-release)
 
 # Check for custom version
 if [[ $2 == "-ver="* ]]; then
 	ver=$(echo "$2" | cut -d'=' -f 2 -s)
+	[[ $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ ]] && ver_int=$(echo ${ver//'*'} | sed 's/\.//g')
 	# Skip stadistics counters for dev and testing (custom version stats).
 	if [[ $(echo $ver | rev | cut -c-1) == "*" || $ver == "alpha" ]]; then
 		ver=${ver//'*'}
@@ -15,42 +26,44 @@ if [[ $2 == "-ver="* ]]; then
 	fi
 fi
 
-# Supported: 22.04 Jammy and 24.04 Noble
-if [[ $distr != "Ubuntu" ]] || ! [[ $osver =~ ^(focal|jammy|noble)$ ]]; then
+# Check for supported OS
+if [[ $distr != "ubuntu" ]] || ! [[ $osver =~ ^(${os_supported_legacy[0]}|${os_supported_stable[0]}|${os_supported_latest[0]})$ ]]; then
 	echo "$(tput setaf 1)"
-	echo "[ERROR] This OS is not supported by Webinoly and could not work properly. $(tput dim)(${distr} '${osver}')"
+	echo "[ERROR] Operating system not supported! $(tput dim)(${distr} '${osver}')"
 	echo "$(tput sgr0)"
 	sudo rm weby
 	exit 1
 
-# Block new installs for: 20.04 Focal (can be installed before 1.19.1) (April 2025 EOL)
-elif [[ $osver == "focal" && $1 != "upd" && -n $ver && $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ && $(echo ${ver//'*'} | sed 's/\.//g') -ge 1191 ]]; then
-	echo "$(tput setaf 1)"
-	echo "[ERROR] Ubuntu 20.04 is not supported on this version of Webinoly!"
-	echo "$(tput sgr0)"
-	sudo rm weby
-	exit 1
-elif [[ $osver == "focal" && $1 != "upd" && -n $ver && $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ && $(echo ${ver//'*'} | sed 's/\.//g') -lt 1191 ]]; then
-	echo "$(tput setaf 1)"
-	echo "[WARNING] You should consider a newer Ubuntu version! $(tput dim)(24.04 or 22.04 are recommended instead)"
-	echo "$(tput sgr0)"
-	
-# 20.04 Focal just for updates, no new installations after 1.19.1
-elif [[ $osver == "focal" && $1 != "upd" ]]; then
-	echo "$(tput setaf 1)"
-	echo "[ERROR] Ubuntu 20.04 is not supported for new installations! $(tput dim)(24.04 or 22.04 are recommended instead)"
-	echo "$(tput sgr0)"
-	sudo rm weby
-	exit 1
+# Block new installs for oldest legacy Ubuntu supported, only updates are allowed...
+elif [[ $osver == ${os_supported_legacy[0]} && $1 != "upd" ]]; then
+	# Old Webinoly versions are allowed...
+	if [[ -n $ver_int && $ver_int -gt $(echo ${os_supported_legacy[2]} | sed 's/\.//g') ]]; then
+		echo "$(tput setaf 1)"
+		echo "[ERROR] Sorry, Ubuntu '${os_supported_legacy[1]}' is no longer supported for new installs."
+		echo "$(tput dim)Webinoly ${os_supported_legacy[2]} was the last version with full support."
+		echo "$(tput dim)Use only if absolutely needed — at your own risk."
+		echo "$(tput sgr0)"
+		sudo rm weby
+		exit 1
+	elif [[ -n $ver_int && $ver_int -le $(echo ${os_supported_legacy[2]} | sed 's/\.//g') ]]; then
+		echo "$(tput setaf 1)"
+		echo "[WARNING] Legacy mode. Use Ubuntu ${os_supported_stable[1]} or newer!"
+		echo "$(tput dim)Use only if absolutely needed — at your own risk."
+		echo "$(tput sgr0)"
+	else
+		# No new installations with the latest Webinoly...
+		echo "$(tput setaf 1)"
+		echo "[ERROR] Sorry, Ubuntu '${os_supported_legacy[1]}' is no longer supported for new installs."
+		echo "$(tput dim)Please use Ubuntu ${os_supported_stable[1]} or newer!"
+		echo "$(tput sgr0)"
+		sudo rm weby
+		exit 1
+	fi
 
-# 24.04 Noble is supported only after 1.18.0
-elif [[ $osver == "noble" && -n $ver && $(echo ${ver//'*'} | sed 's/\.//g') =~ ^[0-9]+$ && $(echo ${ver//'*'} | sed 's/\.//g') -lt 1180 ]]; then
-	#noble - 1.18.0
-	#jammy - 1.16.6
-	#focal - 1.12.0
-	#bionic - 1.4.2
+# Newest Ubuntu supported only after this version...
+elif [[ $osver == ${os_supported_latest[0]} && -n $ver_int && $ver_int -lt $(echo ${os_supported_latest[2]} | sed 's/\.//g') ]]; then
 	echo "$(tput setaf 1)"
-	echo "[ERROR] Ubuntu 24.04 (Noble) is not supported by this version of Webinoly!"
+	echo "[ERROR] This Webinoly version does not support Ubuntu ${os_supported_latest[1]}."
 	echo "$(tput sgr0)"
 	sudo rm weby
 	exit 1
